# Import Libraries

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

# Class Fuzzy AHP

In [2]:
class Fuzzy_AHP:
    def __init__(self, data):#constructor
        self.data = data
        self.fuzzifier = {1:(1,1,1), 2:(1,2,3), 3:(2,3,4), 4:(3,4,5), 5:(4,5,6), 6:(5,6,7), 7:(6,7,8), 8:(7,8,9), 9:(9,9,9),
            1/2:(1/3,1/2,1), 1/3:(1/4,1/3,1/2), 1/4:(1/5,1/4,1/3), 1/5:(1/6,1/5,1/4),
            1/6:(1/7,1/6,1/5), 1/7:(1/8,1/7,1/6), 1/8:(1/9,1/8,1/7), 1/9:(1/9,1/9,1/9)}
        self.geometric_mean = []
        self.geom_sum = None
        self.fuzzy_weights = None
        self.weights = None
    
    def fuzzification(self):#fuzzify
        for i in self.data.columns[1:]:
            self.data[i] = self.data[i].map(self.fuzzifier)
            
        display(self.data)
            
    def calc_geometric_mean(self):#calc geometric mean
        for i in range(len(self.data)):
            a,b,c=1,1,1
            for i in (self.data.iloc[i,1:]):
                a*=i[0]
                b*=i[1]
                c*=i[2]
            self.geometric_mean.append((a**0.25,b**0.25,c**0.25))       
        print('\nGeometric Mean :\n', self.geometric_mean)
        
        self.geom_sum = np.flip(1/np.sum(np.array(self.geometric_mean), axis=0))
        print('\nGeometric Mean Sum :', self.geom_sum)
        
    def calc_fuzzy_weights(self):#calc fuzzy weights
        self.fuzzy_weights = self.geometric_mean * self.geom_sum
        print('\nFuzzy Weights :\n', self.fuzzy_weights)
        
    def defuzzification(self):#defuzzify weights
        self.weights = np.average(self.fuzzy_weights, axis=1)
        self.weights = self.weights / np.sum(self.weights)
        print('\nDefuzzified Weights :', self.weights)
        
    def RUN_ALL(self):#run all methods
        self.fuzzification()
        self.calc_geometric_mean()
        self.calc_fuzzy_weights()
        self.defuzzification()

# Import Data

In [3]:
data = pd.read_excel('Fuzzy_AHP_1.xlsx')
#data = pd.read_excel('Fuzzy_AHP_2.xlsx')
data

Criterias      Cost   Storage  Camera  Looks
0               Cost  1.000000  3.000000     5.0      7
1            Storage  0.333333  1.000000     4.0      6
2       Battery Life  0.200000  0.250000     1.0      5
3  Camera Resolution  0.142857  0.166667     0.2      1

# Create Object

In [4]:
fuzzy_ahp_object = Fuzzy_AHP(data)
fuzzy_ahp_object.RUN_ALL()

Criterias                                               Cost  \
0               Cost                                          (1, 1, 1)   
1            Storage                    (0.25, 0.3333333333333333, 0.5)   
2       Battery Life                   (0.16666666666666666, 0.2, 0.25)   
3  Camera Resolution  (0.125, 0.14285714285714285, 0.16666666666666666)   

                                           Storage  \
0                                        (2, 3, 4)   
1                                        (1, 1, 1)   
2                  (0.2, 0.25, 0.3333333333333333)   
3  (0.14285714285714285, 0.16666666666666666, 0.2)   

                             Camera      Looks  
0                         (4, 5, 6)  (6, 7, 8)  
1                         (3, 4, 5)  (5, 6, 7)  
2                         (1, 1, 1)  (4, 5, 6)  
3  (0.16666666666666666, 0.2, 0.25)  (1, 1, 1)


Geometric Mean :
 [(2.6321480259049848, 3.2010858729436795, 3.7224194364083982), (1.3915788418568702, 1.681792830507429, 2.0453117446175235), (0.6042750794713536, 0.7071067811865476, 0.8408964152537145), (0.23356898886410005, 0.2626909894424158, 0.3021375397356768)]

Geometric Mean Sum : [0.14470178 0.170862   0.20569483]

Fuzzy Weights :
 [[0.3808765  0.54694393 0.76568243]
 [0.20136393 0.28735448 0.42071005]
 [0.08743968 0.12081768 0.17296804]
 [0.03379785 0.04488391 0.06214813]]

Defuzzified Weights : [0.54192324 0.29101836 0.12199265 0.04506576]
